CREATE TABLE pessoa (
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	ativo TINYINT(1)  NOT NULL,
	logradouro VARCHAR(100)  NOT NULL,
  numero  VARCHAR(4)  NOT NULL,
  complemento VARCHAR(50)  NOT NULL,
  bairro VARCHAR(50)  NOT NULL,
  cep VARCHAR(11)  NOT NULL,
  cidade VARCHAR(50)  NOT NULL,
  estado VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
